apiVersion: v1
kind: Secret
metadata:
  name: jwt-key-0
  namespace: kong-app
  labels:
    konghq.com/credential: enhanced-jwt
data:
  algorithm: UlMyNTY=
  claims_to_verify: ZXhwLG5iZg==
  key: YTNmYzMwNDliMzYyNDlhOGM5Zjg4OTFjYjEyNzI0M2M=
  kongCredType: and0
  rsa_public_key: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF0RnhKbHp0cDBTT2syVzQwdDAxZgp4WE96clR1LzZ2M2NCanBuaGR6RFZTb1NQQ095TldGN2lTWlFUTzhxWXROV21ZVVFBUU1ZSGVFKytZejR1dDBBCjFCaGt0aE9vU2gwTlV0K002M0xVWU8rOU0yVXo1ZFo5WDNEa3o1bTFKVkVzcFJGMTFKRXFuTE1NdlErS1JveksKaHliMzFNK0hPcVFRSGZsdHVjRDdJUm9sVUthVkE4aFo5NjR0MTJMZGdWYXhoNU9kMXFhMkdidCs3bnJ2OWJJbgpIT1hzWkFaaVRGMUpyWmpiNXh6Umw1L3pobm85aVBHNEZJanNlaFdQcU5lZFBoVVhyY2ZhL2E5MGV2MXd5ajNHCmFxUndqWXZ2MmpHSlY1RlJtYmRMZk56UVd5TzlRdEVnOGd4d1phdkpsODFHK1YyaEVoaXZKZGV3cDBlMjIzYzMKd3dJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-key-1
  namespace: kong-app
  labels:
    konghq.com/credential: enhanced-jwt
data:
  algorithm: UlMyNTY=
  claims_to_verify: ZXhwLG5iZg==
  key: YTM2YzMwMzliMzYyNDlhM2M5Zjg4OTEwYjEyNzI0M2M=
  kongCredType: and0
  rsa_public_key: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFwZDRmeWNoLzlsSVNGV0dFMlRFTApXdGU0NTBNSkRneEpZYVEwR3MzWnBEeHVtSVIwTlROMFJGK205NzBldFRWN05TbXhqanpxamd6bmZGT2lyNGg4CnNUQnUxajAxZlZDQzlnaTZxOVcxeUxQU0tPYzR4RzI2ME1IcDdTakF1Q1ZCeEQ0MEdxQmk1Z2lENnVLTUdLQnUKL0xnZXFWanVuOUpIQnRpcFluc2p0eElJZ09Nb21XencydnVCUEhKbm1uVk53eWxiTFMxbThyMWpXcUZiM0FGVQpGc0pTODRhL1J6OGMvUmMrYjFiNkFiQ3FjVjJ0ajRGWiszK1BxZGlaSjNIRHJzbFNhRzh3Zm1BcDZ0L2h5UHE0CmlCN3dQSkRsTXRMSmYwdkplRzZLdU1POGhScXJWTjNDckw5ekZLclAyUEk3b1hONHI5ZER1dk9xTG00R2dkRUkKQXdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: consumer-user0
  namespace: kong-app
  annotations:
    kubernetes.io/ingress.class: kong
username: user0
credentials:
- jwt-key-0
#- jwt-key-1
